### ISSUE TITLE
.env file not being picked up

### ISSUE THREAD

**Issue by retorquere** [whiskyechobravo/kerkoapp#1]
I have a `.env` file in the same directory as the `kerkoapp.py`, but when I run 

```
python kerkoapp.py
```

I get

```
Traceback (most recent call last):
  File "kerkoapp.py", line 5, in <module>
    from app import create_app
  File "/app/app/__init__.py", line 11, in <module>
    from .config import CONFIGS
  File "/app/app/config.py", line 20, in <module>
    class Config():
  File "/app/app/config.py", line 21, in Config
    SECRET_KEY = env.str('SECRET_KEY')
  File "/usr/local/lib/python3.7/site-packages/environs.py", line 53, in method
    'Environment variable "{}" not set'.format(proxied_key or parsed_key)
environs.EnvError: Environment variable "SECRET_KEY" not set
```

my current .env is simply what's in the README:

```
FLASK_APP=kerkoapp.py
FLASK_ENV=production
SECRET_KEY=YYYYYYYYY
KERKO_TITLE="Kerko Demo"
KERKO_ZOTERO_API_KEY=XXXXX
KERKO_ZOTERO_LIBRARY_ID=2348869
KERKO_ZOTERO_LIBRARY_TYPE=group
KERKO_CSL_STYLE=apa
KERKO_PRINT_ITEM_LINK=True
KERKO_PRINT_CITATIONS_LINK=True
KERKOAPP_EXCLUDE_DEFAULT_FACETS=facet_tag,facet_link
KERKOAPP_COLLECTION_FACETS="KY3BNA6T:110:Topic; 7H2Q7L6I:120:Field of study; JFQRH4X2:130:Type of contribution"
```

**Comment by davidlesieur** [comment]
Have you tried running the following command instead? (from the same directory)

```
flask run
```

**Comment by retorquere** [comment]
That works, thanks! Now just to get the port mapped through Docker. I'm working on a Dockerfile for kerkoapp -- interested?

**Comment by retorquere** [comment]
Wait -- your README says to run `flask run`. Sorry! Don't know how I missed that.

**Comment by davidlesieur** [comment]
> I'm working on a Dockerfile for kerkoapp -- interested?

Yes!

**Comment by retorquere** [comment]
I'll open a PR as soon as I have it working.

**Comment by mmoole** [comment]
I am sorry to say that I have the same problem when trying to run kerkoapp.
I am using a virtualenv and that is activated and has all packages installed.

Whatever is in the file dotenv.env does not get picked up. 
I suspect something with permissions and/or paths...? It is (not) running on MacOS Catalina 10.15.6 with python per brew, version 3.8.2.

```
╰(kerko_aff_env)─λ flask run                                                                                                          0 < 00:00:00 < 17:19:41
 * Serving Flask app "kerkoapp.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/username/Environments/kerko_aff_env/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/username/projekte/devc2c/Kerko_test1/kerkoapp/kerkoapp.py", line 4, in <module>
    from app import create_app
  File "/Users/username/projekte/devc2c/Kerko_test1/kerkoapp/app/__init__.py", line 11, in <module>
    from .config import CONFIGS
  File "/Users/username/projekte/devc2c/Kerko_test1/kerkoapp/app/config.py", line 21, in <module>
    class Config():
  File "/Users/username/projekte/devc2c/Kerko_test1/kerkoapp/app/config.py", line 24, in Config
    SECRET_KEY = env.str('SECRET_KEY')
  File "/Users/username/Environments/kerko_aff_env/lib/python3.8/site-packages/environs/__init__.py", line 75, in method
    raise EnvValidationError('Environment variable "{}" not set'.format(source_key), [message])
environs.EnvValidationError: Environment variable "SECRET_KEY" not set
```

that's the content of the folder:
```
/Users/username/projekte/devc2c/Kerko_test1/kerkoapp (master …4)
╰(kerko_aff_env)─λ ll                                                                                                                 1 < 00:00:01 < 17:22:57
total 136
-rw-r--r--   1 username  staff   1,6K 30 Aug 13:12 CHANGELOG.md
-rw-r--r--   1 username  staff   370B 30 Aug 13:12 Dockerfile
-rw-r--r--   1 username  staff   1,5K 30 Aug 13:12 LICENSE.txt
-rw-r--r--@  1 username  staff   1,3K 30 Aug 13:12 Makefile
-rw-r--r--   1 username  staff    21K 30 Aug 13:12 README.md
drwxr-xr-x   3 username  staff    96B 30 Aug 17:16 __pycache__/
drwxr-xr-x  10 username  staff   320B 30 Aug 16:03 app/
-rw-r--r--   1 username  staff   121B 30 Aug 13:12 babel.cfg
-rw-r--r--@  1 username  staff   576B 30 Aug 15:50 dotenv.env
-rw-r--r--   1 username  staff   385B 30 Aug 13:12 dotenv.sample
-rw-r--r--   1 username  staff   867B 30 Aug 13:12 kerkoapp.py
drwxr-xr-x   6 username  staff   192B 30 Aug 13:12 requirements/
```
BUT as I just found out: it seems to work if I rename the env file to `.flaskenv` !

**Comment by davidlesieur** [comment]
Ah, yes, `.flaskenv` can work equally well, although the Kerko README only mentions `.env`. Your folder appears to contain a `dotenv.env` file (which is not recognized) instead of the expected `.env`. 

Per [Flask's docs](https://flask.palletsprojects.com/en/1.1.x/cli/#environment-variables-from-dotenv), if `.env` exists its variable will override those of `.flaskenv`. It also says that `.flaskenv` is normally used for public variables, so for that reason I recommend that you put at least your private keys in `.env` instead of `.flaskenv`.

**Comment by mmoole** [comment]
ah, pardon! I was reading too fast, and copied `dotenv.sample` to `dotenv.env` but thought it being `.env`. Seriously, pardon for that 👍 🤪

**Comment by davidlesieur** [comment]
That's fine. It reminded me that `.flaskenv` was also possible, something I had completely forgotten! 😉

**Comment by Samandar7** [comment]
does not work

raise EnvValidationError('Environment variable "{}" not set'.format(source_key), [message])
environs.EnvValidationError: Environment variable "bot_token" not set

**Comment by Samandar7** [comment]
does not work

**Comment by davidlesieur** [comment]
@Samandar7 I have no idea what that "bot_token" variable is. Are you sure this is a Kerko issue? Also, this issue is closed, thus if the problem persists I suggest that you open a new issue and provide more details so that we can reproduce the problem.
