### ISSUE TITLE
Zotero API error

### ISSUE THREAD

**Issue by saurabhsindhu** [whiskyechobravo/kerkoapp#42]
The website https://transplantid.net was running fine for last 6 months but when I ran sync command today after cleaning the index it's giving the below error. It's API request error from Zotero API. 

[2023-11-05 04:31:13,137] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:31:13,137] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:33:13,236] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:34:13,420] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:34:13,420] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:36:13,496] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:37:13,677] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:37:13,677] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:39:13,777] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:40:14,038] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:40:14,039] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:42:14,139] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:43:14,340] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:43:14,341] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:45:14,423] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:46:14,598] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:46:14,599] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:48:14,698] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:49:14,963] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:49:14,964] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:51:15,064] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:52:15,256] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:52:15,257] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:54:15,353] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:55:15,536] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:55:15,536] WARNING in zotero: The Zotero API request has failed in _next_batch. New attempt in 120 seconds...
[2023-11-05 04:57:15,636] INFO in zotero: Requesting up to 100 updated items since version 7868, starting at position 0...
[2023-11-05 04:58:15,876] WARNING in zotero: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

[2023-11-05 04:58:15,877] ERROR in zotero: The maximum number of API call attempts to Zotero has been reached. Stopping.
Traceback (most recent call last):
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/sync/zotero.py", line 329, in __next__
    return self._next_item()
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/sync/zotero.py", line 355, in _next_item
    zotero_item = next(self.iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/pyzotero/zotero.py", line 411, in _retrieve_data
    self.request.raise_for_status()
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/cli.py", line 20, in execution_time_logger
    return_value = wrapped(*args, **kwargs)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/cli.py", line 46, in sync
    sync_cache()
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/sync/cache.py", line 62, in sync_cache
    for item in zotero.Items(zotero_credentials, since=since, formats=list(formats) + ['data']):
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/sync/zotero.py", line 331, in __next__
    self._next_batch()
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/sync/zotero.py", line 40, in retry_zotero
    return wrapped(*args, **kwargs)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/kerko/sync/zotero.py", line 349, in _next_batch
    self.zotero_batch = getattr(self.zotero_credentials, self.method)(**params)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/pyzotero/zotero.py", line 178, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/pyzotero/zotero.py", line 413, in _retrieve_data
    error_handler(self, self.request)
  File "/home/transpla/virtualenv/public_html/transplantIDlib/3.9/lib/python3.9/site-packages/pyzotero/zotero.py", line 1644, in error_handler
    raise ze.HTTPError(err_msg(req))
pyzotero.zotero_errors.HTTPError: 
Code: 504
URL: https://api.zotero.org/users/4330545/items?since=7868&start=0&limit=100&sort=dateAdded&direction=asc&include=bib%2Cbibtex%2Ccitation%2Ccoins%2Cdata%2Cris&style=https%3A%2F%2Fdocs.edtechhub.org%2Fstatic%2Fdist%2Fcsl%2Feth_apa.xml%3F202012301815&format=json
Method: GET
Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

**Comment by davidlesieur** [comment]
I can see from the requested URL that you are using a CSL style that's externally hosted (`https://docs.edtechhub.org/static/dist/csl/eth_apa.xml`). Not sure that is the reason behind the error, but should that style become unavailable, synchronization will certainly fail. My understanding is that your site is based on code forked from theirs, so if you want to use that CSL style, you have to make it available from your own web server, and change the Kerko configuration to use it instead of `https://docs.edtechhub.org/static/dist/csl/eth_apa.xml`. Please let us know if that solves the problem!

**Comment by saurabhsindhu** [comment]
Thanks, David. It partly solves the problem as I was able to sync the data from Zotero after making config and adding https://transplantid.net/static/dist/csl/eth_apa.xml but the title of the citations are missing as it was displaying earlier for https://transplantid.net/

Please let me know how to solve it as I have limited knowledge about CSL Style development.

**Comment by davidlesieur** [comment]
Issue was avoided by setting the `kerko.zotero.batch_size` parameter to 20.
